### ISSUE TITLE
Add link to a repo that uses this tool? As an example

### ISSUE THREAD

**Issue by voxpelli** [LinusU/ts-readme-generator#4]
Would be neat to see the output of this module

**Comment by LinusU** [comment]
That's a great idea! There are quite a few real worlds example in [the `fixtures` folder](https://github.com/LinusU/ts-readme-generator/tree/master/fixtures), but I'll also add links to projects in the readme!

**Comment by LinusU** [comment]
Sorry for the long delay, this is now fixed! 🎉 

https://github.com/LinusU/ts-readme-generator#examples
